model:
  init_name: whisper-large-v3-turbo
  bfloat16: False # If this is set, mixed_precision_training will use bfloat16
dataset:
  train_datasets: [i4ds/sds-stt-spc-train-val-v4, i4ds/srg-full-train-val-v2, i4ds/mozilla-cv-13-long-text-de]
  select_n_per_t_ds: [null, null, 15000] # How many rows to sample from the respective dataset per training run.
  groupby_col: [null, null] # If set, it will preform a groupby sample per column in the respective train dataset, similar to pandas groupby.sample but with training data. Total number of samples is select_n_per_t_ds * n_groups.
  val_datasets: [i4ds/sds-stt-spc-train-val-v4, i4ds/srg-full-train-val-v2, i4ds/mozilla-cv-13-long-text-de]
  select_n_per_v_ds: [500, 500, 500] # How many rows to sample from the respective dataset per training run.
  train_split_name: "train" # Split name to use for the train dataset.
  valid_split_name: "validation" # Split name to use for the validation dataset.
  no_timestamp_training: True # Whether to use no timestamps for training.
  max_prompt_length: 223 # The maximum number of tokens to use for the prompt (Fixed by whisper).
  prompt_use_rate: 0.5 # How often to use the prompt.
  no_timestamp_rate: 0.5 # How often to use no timestamps.
  batch_size: 16
  batch_size_eval: 16
lr_scheduler:
  type: linear
  warmup_steps: 128 # If bigger than 1, then it's the total number of steps, else the ratio of total steps to use as warmup.
optimizer:
  type: adamw
  8bit: True
  params:
    lr: 2.0e-4
    weight_decay: 0.1
    betas: [0.9, 0.98]
    eps: 1.0e-9
    amsgrad: False
training:
  accum_grad_steps: 16
  train_only_decoder: False # If true, disable the grads of the encoder
  train_only_encoder: False # If true, disable the grads of the decoder
  max_grad_norm: 1.0
  stochastic_depth: 0.0 # Stochastic depth, used in whisper. See https://arxiv.org/abs/1603.09382
  epochs: 2
  eval_steps: 0.25 # % of each epoch to do validation.
  save_all_checkpoints: False
  mixed_precision_training: True
  mp_dtype: fp16
  gradient_checkpointing_encoder: True # If there should be gradient checkpointing in the encoder.
  gradient_checkpointing_encoder_last_only: False # Somehow, does not save a lot of memory (~1%).
  gradient_checkpointing_decoder: True # If there should be gradient checkpointing in the decoder.
augmentation: # Data augmentations, see the whisper paper for more details
  spec_augment:
    apply: True
    time_mask_param: 100
    p: 1.0
    freq_mask_param: 27
    time_warp_w: 80
  audio_augment: # Audio augmentations by reducing audio quality (white noise, high-pass filter, and low-pass filter).
    apply: False
    lpf: # Low pass filter
      p: 0.1
      sample_rate: 16000
      target_rate: 16000
      min_cutoff_freq: 3340
      max_cutoff_freq: 7500
    hpf: # High pass filter
      p: 0.1
      sample_rate: 16000
      target_rate: 16000
      min_cutoff_freq: 20
      max_cutoff_freq: 128
    acn:  # Colored noise
      p: 0.0
      sample_rate: 16000
      target_rate: 16000
      min_snr_in_db: 25
      max_snr_in_db: 99
seed: 123
save_dir: output